### ISSUE TITLE
Working Group To Fix For Windows

### ISSUE THREAD

**Issue by ScriptTiger** [ScriptTiger/hosts#1]
Welcome, @XhmikosR and @funilrys! @funilrys, I know you've got a lot of stuff going on, but I saw you submitted some PRs to help @XhmikosR out and thought maybe you can both finish working together here and we can merge it back in later since Steven prefers to delegate Windows-related tasks off of the repo. To be fair, he does have a lot of stuff going on, both professionally and personally, so I think it's best just for everyone to stay calm and just wrap things up in this safe space. After you guys have something you're happy with, there won't be any issues with merging it back later, it's just the discussions Steven doesn't like because it's off topic from his point of view, so we should respect that for now and just keep the discussions elsewhere as an independent working group.

**Comment by XhmikosR** [comment]
TBH I was totally put off by Steven's comment. I'm so fed up with the elitist behavior macOS/Linux users have against everyone else.

The fact that I use Windows too, does not mean I don't use any other OS. But I want things to work equally good whenever I can.

So, I don't know if I'll bother any further with this project, sorry.

That being said, everything should work fine after the recent changes, minus that sorting issue that I couldn't figure out why it happens and what one can do to prevent this (seemingly) OS-related behavior.

**Comment by ScriptTiger** [comment]
Well, I'm sorry you feel that way. You'll inevitably always run into conflicts of opinions and interests in open source, but that's really what makes collaborative coding like this so awesome. I do everything I do here for the people using whatever I'm working on and that can benefit from it, not for any particular person, programmer, curator, etc. And from my own projects I know for a fact there are a lot of Windows users utilizing Steven's lists and that's why I've tried to do several projects to make it more accessible to everyone. I think I have made a lot of progress in those respects, but really making the one bit of Windows in Steven's repo actually work as expected would benefit a lot of people.

I've had my fair share of head-butting with him and know Steven can be rather opinionated in the issues, but I have never seen him reject a solid PR that has no logical reason to be rejected. In fact, when I first sent in an issue to his repo to see if people might gain any benefit from my AutoUpdate script, he was the one that immediately suggested I PR his README to tell people about it because there's no denying that a large number of his issues come from Windows users and most of them had their problems solved just by using my script. It was even the Windows community that spearheaded getting Steven's script to support compression, since that tends to be a bigger issue for Windows than other systems. And now multiple OSes benefit from that, not just Windows users.

I mean all in all this may just be a small and simple issue, but I always follow my principles and, like you, think things should just work correctly, period. I don't care if someone is the owner of a repo or not, if I find benefit from something they are putting out and also find room for improvement, I'll put out PRs regardless of my personal opinions about any person. Ultimately open source is about more than any individual and is about the democratization and evolution of ideas, regardless of anything else. Lending yourself to be put off by any person or group is a taint to the very ethos of open source, and even Steven knows and respects that. He's just short-tempered sometimes and talks smack, but he'll still accept a good PR even if he doesn't like someone or something that spawned it. I think the fact that he still accepts PRs from me proves that, given the amount of issues he's closed and locked on me.

**Comment by ScriptTiger** [comment]
@funilrys, is there a way to implement an ordered data structure that wouldn't change everything and get rejected by Steven? I'm not sure if this would require a change to all of the JSONs or not to be JSON arrays or something else, but if it does we can pretty much just give up if it requires changing the JSONs. But basically the problem is the object mappings are not ordered, so they come out a different order on Windows and Linux because as far as Python is concerned they don't have an order and the order you see in the files is just up to that specific implementation of Python. So they would need to be forced into an ordered structure to keep it consistent through every implementation of Python if the order is important and not just an object mapping, which it is now.

I think this actually is pretty important to verify the integrity of the files. Obviously most of us trust Steven, but sometimes people may just want to verify and run the script on a Windows machine to check it against the integrity of Steven's. Obviously checking the integrity would require the same order, otherwise the diffs would be wildly different if they have the same data or not, like what's happening now. It makes the process not transparent to people using different Python implementations from Steven, which is an important point for something in the security space, I feel.

**Comment by funilrys** [comment]
@ScriptTiger I'm going to create the PR with the patch which should fix that behavior by forcing a unification.

**Comment by ScriptTiger** [comment]
Nice, I'm excited to try it out! Thanks for seeing this to the end!

**Comment by ScriptTiger** [comment]
@XhmikosR, I'll wait to hear back from you on your results with the latest release from Steven before I close this repo.

**Comment by XhmikosR** [comment]
Worked fine when I tried the upstream master branch yersterday. Only a few differences :)

**Comment by ScriptTiger** [comment]
The differences that you got, they are just differences in some hosts listed just due to the fact that the sources are always curating, or any actual structural differences to file ordering?

**Comment by XhmikosR** [comment]
All good. They are because there are more changes committed but there hasn't been a patch updating the dist files. Sorting is now fine.

**Comment by ScriptTiger** [comment]
Roger that. Thanks again, @XhmikosR and @funilrys! I'm closing this repo now.
